# Generated by Django 3.0.4 on 2020-04-18 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_wlfare', '0002_registrationmodel_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationmodel',
            name='status',
            field=models.CharField(default=False, max_length=30),
        ),
    ]
